<?php
/**
 * ActivitycommentcommentIdpositionsCompensationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ActivitycommentcommentIdpositionsCompensationTest Class Doc Comment
 *
 * @category    Class
 * @description ActivitycommentcommentIdpositionsCompensation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActivitycommentcommentIdpositionsCompensationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ActivitycommentcommentIdpositionsCompensation"
     */
    public function testActivitycommentcommentIdpositionsCompensation()
    {
    }

    /**
     * Test attribute "contract_length"
     */
    public function testPropertyContractLength()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "formatted_pay_rate"
     */
    public function testPropertyFormattedPayRate()
    {
    }

    /**
     * Test attribute "formatted_salary_from"
     */
    public function testPropertyFormattedSalaryFrom()
    {
    }

    /**
     * Test attribute "formatted_salary_to"
     */
    public function testPropertyFormattedSalaryTo()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "pay_rate"
     */
    public function testPropertyPayRate()
    {
    }

    /**
     * Test attribute "salary_from"
     */
    public function testPropertySalaryFrom()
    {
    }

    /**
     * Test attribute "salary_to"
     */
    public function testPropertySalaryTo()
    {
    }

    /**
     * Test attribute "salary_type"
     */
    public function testPropertySalaryType()
    {
    }
}
