<?php
/**
 * Body38Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Body38Test Class Doc Comment
 *
 * @category    Class
 * @description request body
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Body38Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body38"
     */
    public function testBody38()
    {
    }

    /**
     * Test attribute "assignee_id"
     */
    public function testPropertyAssigneeId()
    {
    }

    /**
     * Test attribute "attendee_ids"
     */
    public function testPropertyAttendeeIds()
    {
    }

    /**
     * Test attribute "candidate_ids"
     */
    public function testPropertyCandidateIds()
    {
    }

    /**
     * Test attribute "category_ids"
     */
    public function testPropertyCategoryIds()
    {
    }

    /**
     * Test attribute "company_ids"
     */
    public function testPropertyCompanyIds()
    {
    }

    /**
     * Test attribute "contact_ids"
     */
    public function testPropertyContactIds()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "creator_id"
     */
    public function testPropertyCreatorId()
    {
    }

    /**
     * Test attribute "custom_name"
     */
    public function testPropertyCustomName()
    {
    }

    /**
     * Test attribute "due_date_start"
     */
    public function testPropertyDueDateStart()
    {
    }

    /**
     * Test attribute "due_date_end"
     */
    public function testPropertyDueDateEnd()
    {
    }

    /**
     * Test attribute "insert_timestamp"
     */
    public function testPropertyInsertTimestamp()
    {
    }

    /**
     * Test attribute "kpi_action_id"
     */
    public function testPropertyKpiActionId()
    {
    }

    /**
     * Test attribute "main_entity_type"
     */
    public function testPropertyMainEntityType()
    {
    }

    /**
     * Test attribute "meeting_location"
     */
    public function testPropertyMeetingLocation()
    {
    }

    /**
     * Test attribute "meeting_room"
     */
    public function testPropertyMeetingRoom()
    {
    }

    /**
     * Test attribute "position_ids"
     */
    public function testPropertyPositionIds()
    {
    }

    /**
     * Test attribute "other_attendee"
     */
    public function testPropertyOtherAttendee()
    {
    }

    /**
     * Test attribute "send_invitation"
     */
    public function testPropertySendInvitation()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }
}
