<?php
/**
 * InlineResponse200109Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200109Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200109
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200109Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200109"
     */
    public function testInlineResponse200109()
    {
    }

    /**
     * Test attribute "primary_approver_id"
     */
    public function testPropertyPrimaryApproverId()
    {
    }

    /**
     * Test attribute "primary_approver_name"
     */
    public function testPropertyPrimaryApproverName()
    {
    }

    /**
     * Test attribute "primary_approver_email"
     */
    public function testPropertyPrimaryApproverEmail()
    {
    }

    /**
     * Test attribute "secondary_approver_id"
     */
    public function testPropertySecondaryApproverId()
    {
    }

    /**
     * Test attribute "secondary_approver_name"
     */
    public function testPropertySecondaryApproverName()
    {
    }

    /**
     * Test attribute "secondary_approver_email"
     */
    public function testPropertySecondaryApproverEmail()
    {
    }

    /**
     * Test attribute "approval_required_mode"
     */
    public function testPropertyApprovalRequiredMode()
    {
    }

    /**
     * Test attribute "use_timesheet_for_payroll"
     */
    public function testPropertyUseTimesheetForPayroll()
    {
    }

    /**
     * Test attribute "use_timesheet_for_invoicing"
     */
    public function testPropertyUseTimesheetForInvoicing()
    {
    }

    /**
     * Test attribute "use_timesheet_for_expenses"
     */
    public function testPropertyUseTimesheetForExpenses()
    {
    }

    /**
     * Test attribute "fixed_timesheet"
     */
    public function testPropertyFixedTimesheet()
    {
    }
}
