<?php
/**
 * InlineResponse20029ContentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20029ContentTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20029Content
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20029ContentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20029Content"
     */
    public function testInlineResponse20029Content()
    {
    }

    /**
     * Test attribute "close_date"
     */
    public function testPropertyCloseDate()
    {
    }

    /**
     * Test attribute "employment_type"
     */
    public function testPropertyEmploymentType()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "floated_job"
     */
    public function testPropertyFloatedJob()
    {
    }

    /**
     * Test attribute "head_count"
     */
    public function testPropertyHeadCount()
    {
    }

    /**
     * Test attribute "position_id"
     */
    public function testPropertyPositionId()
    {
    }

    /**
     * Test attribute "job_title"
     */
    public function testPropertyJobTitle()
    {
    }

    /**
     * Test attribute "job_type"
     */
    public function testPropertyJobType()
    {
    }

    /**
     * Test attribute "open_date"
     */
    public function testPropertyOpenDate()
    {
    }
}
