<?php
/**
 * InlineResponse20038Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20038Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20038
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20038Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20038"
     */
    public function testInlineResponse20038()
    {
    }

    /**
     * Test attribute "contract_length"
     */
    public function testPropertyContractLength()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "formatted_pay_rate"
     */
    public function testPropertyFormattedPayRate()
    {
    }

    /**
     * Test attribute "formatted_salary_from"
     */
    public function testPropertyFormattedSalaryFrom()
    {
    }

    /**
     * Test attribute "formatted_salary_to"
     */
    public function testPropertyFormattedSalaryTo()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "pay_rate"
     */
    public function testPropertyPayRate()
    {
    }

    /**
     * Test attribute "salary_from"
     */
    public function testPropertySalaryFrom()
    {
    }

    /**
     * Test attribute "salary_to"
     */
    public function testPropertySalaryTo()
    {
    }

    /**
     * Test attribute "salary_type"
     */
    public function testPropertySalaryType()
    {
    }

    /**
     * Test attribute "use_quick_fee_forecast"
     */
    public function testPropertyUseQuickFeeForecast()
    {
    }

    /**
     * Test attribute "quick_fee"
     */
    public function testPropertyQuickFee()
    {
    }

    /**
     * Test attribute "profit"
     */
    public function testPropertyProfit()
    {
    }

    /**
     * Test attribute "job_type"
     */
    public function testPropertyJobType()
    {
    }

    /**
     * Test attribute "employment_type"
     */
    public function testPropertyEmploymentType()
    {
    }

    /**
     * Test attribute "mths_year"
     */
    public function testPropertyMthsYear()
    {
    }

    /**
     * Test attribute "salary_rate_per_month"
     */
    public function testPropertySalaryRatePerMonth()
    {
    }

    /**
     * Test attribute "formatted_salary_rate_per_month"
     */
    public function testPropertyFormattedSalaryRatePerMonth()
    {
    }

    /**
     * Test attribute "annual_salary"
     */
    public function testPropertyAnnualSalary()
    {
    }

    /**
     * Test attribute "formatted_annual_salary"
     */
    public function testPropertyFormattedAnnualSalary()
    {
    }

    /**
     * Test attribute "gross_annual_salary"
     */
    public function testPropertyGrossAnnualSalary()
    {
    }

    /**
     * Test attribute "formatted_gross_annual_salary"
     */
    public function testPropertyFormattedGrossAnnualSalary()
    {
    }

    /**
     * Test attribute "formatted_profit"
     */
    public function testPropertyFormattedProfit()
    {
    }

    /**
     * Test attribute "incentives"
     */
    public function testPropertyIncentives()
    {
    }

    /**
     * Test attribute "exempt_incentives"
     */
    public function testPropertyExemptIncentives()
    {
    }

    /**
     * Test attribute "optional_factors"
     */
    public function testPropertyOptionalFactors()
    {
    }

    /**
     * Test attribute "stat_gov_taxes"
     */
    public function testPropertyStatGovTaxes()
    {
    }

    /**
     * Test attribute "annual_paid_holidays"
     */
    public function testPropertyAnnualPaidHolidays()
    {
    }

    /**
     * Test attribute "working_hours_per_day"
     */
    public function testPropertyWorkingHoursPerDay()
    {
    }

    /**
     * Test attribute "working_days_per_month"
     */
    public function testPropertyWorkingDaysPerMonth()
    {
    }

    /**
     * Test attribute "annual_paid_sick_days"
     */
    public function testPropertyAnnualPaidSickDays()
    {
    }

    /**
     * Test attribute "working_days_per_week"
     */
    public function testPropertyWorkingDaysPerWeek()
    {
    }

    /**
     * Test attribute "working_weeks_per_month"
     */
    public function testPropertyWorkingWeeksPerMonth()
    {
    }

    /**
     * Test attribute "fee_model_name"
     */
    public function testPropertyFeeModelName()
    {
    }

    /**
     * Test attribute "fee_model_type"
     */
    public function testPropertyFeeModelType()
    {
    }

    /**
     * Test attribute "fee_model_detail_job_type"
     */
    public function testPropertyFeeModelDetailJobType()
    {
    }

    /**
     * Test attribute "fee_model_fee_rate"
     */
    public function testPropertyFeeModelFeeRate()
    {
    }

    /**
     * Test attribute "fee_model_gross_annual_salary"
     */
    public function testPropertyFeeModelGrossAnnualSalary()
    {
    }

    /**
     * Test attribute "fee_model_incentives_guarantee"
     */
    public function testPropertyFeeModelIncentivesGuarantee()
    {
    }

    /**
     * Test attribute "fee_model_exempt_incentives"
     */
    public function testPropertyFeeModelExemptIncentives()
    {
    }

    /**
     * Test attribute "fee_model_stat_gov_taxes"
     */
    public function testPropertyFeeModelStatGovTaxes()
    {
    }

    /**
     * Test attribute "fee_model_optional_factor"
     */
    public function testPropertyFeeModelOptionalFactor()
    {
    }

    /**
     * Test attribute "fee_model_comment"
     */
    public function testPropertyFeeModelComment()
    {
    }

    /**
     * Test attribute "fee_model_contract_period"
     */
    public function testPropertyFeeModelContractPeriod()
    {
    }

    /**
     * Test attribute "fee_model_start_date"
     */
    public function testPropertyFeeModelStartDate()
    {
    }

    /**
     * Test attribute "fee_model_invoice_date"
     */
    public function testPropertyFeeModelInvoiceDate()
    {
    }

    /**
     * Test attribute "fee_model_invoice_payment_term"
     */
    public function testPropertyFeeModelInvoicePaymentTerm()
    {
    }

    /**
     * Test attribute "fee_model_fixed_fee_currency"
     */
    public function testPropertyFeeModelFixedFeeCurrency()
    {
    }

    /**
     * Test attribute "fee_model_fixed_fee_amount"
     */
    public function testPropertyFeeModelFixedFeeAmount()
    {
    }

    /**
     * Test attribute "formatted_fee_model_fixed_fee_amount"
     */
    public function testPropertyFormattedFeeModelFixedFeeAmount()
    {
    }

    /**
     * Test attribute "fee_model_fixed_fee_comment"
     */
    public function testPropertyFeeModelFixedFeeComment()
    {
    }

    /**
     * Test attribute "fee_model_retainer_currency"
     */
    public function testPropertyFeeModelRetainerCurrency()
    {
    }

    /**
     * Test attribute "fee_model_retainer_comment"
     */
    public function testPropertyFeeModelRetainerComment()
    {
    }

    /**
     * Test attribute "fee_model_retainer_details"
     */
    public function testPropertyFeeModelRetainerDetails()
    {
    }

    /**
     * Test attribute "fee_model_retainer_total_amount"
     */
    public function testPropertyFeeModelRetainerTotalAmount()
    {
    }

    /**
     * Test attribute "fee_model_no_fee_payable_description"
     */
    public function testPropertyFeeModelNoFeePayableDescription()
    {
    }

    /**
     * Test attribute "interval_base_pay"
     */
    public function testPropertyIntervalBasePay()
    {
    }

    /**
     * Test attribute "formatted_interval_base_pay"
     */
    public function testPropertyFormattedIntervalBasePay()
    {
    }

    /**
     * Test attribute "interval_base_charge"
     */
    public function testPropertyIntervalBaseCharge()
    {
    }

    /**
     * Test attribute "formatted_interval_base_charge"
     */
    public function testPropertyFormattedIntervalBaseCharge()
    {
    }

    /**
     * Test attribute "interval_base_profit"
     */
    public function testPropertyIntervalBaseProfit()
    {
    }

    /**
     * Test attribute "formatted_interval_base_profit"
     */
    public function testPropertyFormattedIntervalBaseProfit()
    {
    }

    /**
     * Test attribute "total_contract_pay"
     */
    public function testPropertyTotalContractPay()
    {
    }

    /**
     * Test attribute "formatted_total_contract_pay"
     */
    public function testPropertyFormattedTotalContractPay()
    {
    }

    /**
     * Test attribute "total_contract_charge"
     */
    public function testPropertyTotalContractCharge()
    {
    }

    /**
     * Test attribute "formatted_total_contract_charge"
     */
    public function testPropertyFormattedTotalContractCharge()
    {
    }

    /**
     * Test attribute "total_contract_profit"
     */
    public function testPropertyTotalContractProfit()
    {
    }

    /**
     * Test attribute "formatted_total_contract_profit"
     */
    public function testPropertyFormattedTotalContractProfit()
    {
    }

    /**
     * Test attribute "time_management"
     */
    public function testPropertyTimeManagement()
    {
    }

    /**
     * Test attribute "pay_interval"
     */
    public function testPropertyPayInterval()
    {
    }

    /**
     * Test attribute "contract_length_type"
     */
    public function testPropertyContractLengthType()
    {
    }

    /**
     * Test attribute "pay_range_from"
     */
    public function testPropertyPayRangeFrom()
    {
    }

    /**
     * Test attribute "pay_range_to"
     */
    public function testPropertyPayRangeTo()
    {
    }

    /**
     * Test attribute "formatted_pay_range_from"
     */
    public function testPropertyFormattedPayRangeFrom()
    {
    }

    /**
     * Test attribute "formatted_pay_range_to"
     */
    public function testPropertyFormattedPayRangeTo()
    {
    }

    /**
     * Test attribute "base_pay_rate"
     */
    public function testPropertyBasePayRate()
    {
    }

    /**
     * Test attribute "formatted_base_pay_rate"
     */
    public function testPropertyFormattedBasePayRate()
    {
    }

    /**
     * Test attribute "on_costs_number"
     */
    public function testPropertyOnCostsNumber()
    {
    }

    /**
     * Test attribute "formatted_on_costs_number"
     */
    public function testPropertyFormattedOnCostsNumber()
    {
    }

    /**
     * Test attribute "on_costs_percentage_in_decimal"
     */
    public function testPropertyOnCostsPercentageInDecimal()
    {
    }

    /**
     * Test attribute "total_pay_rate"
     */
    public function testPropertyTotalPayRate()
    {
    }

    /**
     * Test attribute "formatted_total_pay_rate"
     */
    public function testPropertyFormattedTotalPayRate()
    {
    }

    /**
     * Test attribute "margin_percentage_in_decimal"
     */
    public function testPropertyMarginPercentageInDecimal()
    {
    }

    /**
     * Test attribute "markup_percentage_in_decimal"
     */
    public function testPropertyMarkupPercentageInDecimal()
    {
    }

    /**
     * Test attribute "profit_margin"
     */
    public function testPropertyProfitMargin()
    {
    }

    /**
     * Test attribute "formatted_profit_margin"
     */
    public function testPropertyFormattedProfitMargin()
    {
    }

    /**
     * Test attribute "charge_rate"
     */
    public function testPropertyChargeRate()
    {
    }

    /**
     * Test attribute "formatted_charge_rate"
     */
    public function testPropertyFormattedChargeRate()
    {
    }

    /**
     * Test attribute "total_pay_calculation"
     */
    public function testPropertyTotalPayCalculation()
    {
    }

    /**
     * Test attribute "calculate_charge_using"
     */
    public function testPropertyCalculateChargeUsing()
    {
    }

    /**
     * Test attribute "start_of_week"
     */
    public function testPropertyStartOfWeek()
    {
    }

    /**
     * Test attribute "pay_cycle"
     */
    public function testPropertyPayCycle()
    {
    }

    /**
     * Test attribute "astute_pay_cycle_id"
     */
    public function testPropertyAstutePayCycleId()
    {
    }

    /**
     * Test attribute "astute_rule_group_id"
     */
    public function testPropertyAstuteRuleGroupId()
    {
    }

    /**
     * Test attribute "astute_rate_card_id"
     */
    public function testPropertyAstuteRateCardId()
    {
    }

    /**
     * Test attribute "first_half_of_month"
     */
    public function testPropertyFirstHalfOfMonth()
    {
    }

    /**
     * Test attribute "second_half_of_month"
     */
    public function testPropertySecondHalfOfMonth()
    {
    }

    /**
     * Test attribute "pay_and_charge_incl_overtimes"
     */
    public function testPropertyPayAndChargeInclOvertimes()
    {
    }

    /**
     * Test attribute "allowances_subject_to_stat_govt_taxes"
     */
    public function testPropertyAllowancesSubjectToStatGovtTaxes()
    {
    }

    /**
     * Test attribute "allowances_not_subject_to_stat_govt_taxes"
     */
    public function testPropertyAllowancesNotSubjectToStatGovtTaxes()
    {
    }

    /**
     * Test attribute "contract_based_optional_factors"
     */
    public function testPropertyContractBasedOptionalFactors()
    {
    }

    /**
     * Test attribute "pto_paid_time_off_in_hours"
     */
    public function testPropertyPtoPaidTimeOffInHours()
    {
    }

    /**
     * Test attribute "timesheets_pay_rules"
     */
    public function testPropertyTimesheetsPayRules()
    {
    }

    /**
     * Test attribute "timesheets_pay_rule_exceptions"
     */
    public function testPropertyTimesheetsPayRuleExceptions()
    {
    }

    /**
     * Test attribute "fee_model_invoice_pay_interval"
     */
    public function testPropertyFeeModelInvoicePayInterval()
    {
    }
}
