<?php
/**
 * InlineResponse20040Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20040Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20040
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20040Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20040"
     */
    public function testInlineResponse20040()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "date_format"
     */
    public function testPropertyDateFormat()
    {
    }

    /**
     * Test attribute "deactivated"
     */
    public function testPropertyDeactivated()
    {
    }

    /**
     * Test attribute "display_language"
     */
    public function testPropertyDisplayLanguage()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "email_is_integrated"
     */
    public function testPropertyEmailIsIntegrated()
    {
    }

    /**
     * Test attribute "full_name"
     */
    public function testPropertyFullName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "insert_timestamp"
     */
    public function testPropertyInsertTimestamp()
    {
    }

    /**
     * Test attribute "last_updated_timestamp"
     */
    public function testPropertyLastUpdatedTimestamp()
    {
    }

    /**
     * Test attribute "permission"
     */
    public function testPropertyPermission()
    {
    }

    /**
     * Test attribute "responsibility"
     */
    public function testPropertyResponsibility()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "user_location"
     */
    public function testPropertyUserLocation()
    {
    }

    /**
     * Test attribute "photo_url"
     */
    public function testPropertyPhotoUrl()
    {
    }
}
