<?php
/**
 * InlineResponse20047ContentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20047ContentTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20047Content
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20047ContentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20047Content"
     */
    public function testInlineResponse20047Content()
    {
    }

    /**
     * Test attribute "activity_type"
     */
    public function testPropertyActivityType()
    {
    }

    /**
     * Test attribute "assignee"
     */
    public function testPropertyAssignee()
    {
    }

    /**
     * Test attribute "candidate_first_name"
     */
    public function testPropertyCandidateFirstName()
    {
    }

    /**
     * Test attribute "candidate_last_name"
     */
    public function testPropertyCandidateLastName()
    {
    }

    /**
     * Test attribute "candidate_middle_name"
     */
    public function testPropertyCandidateMiddleName()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "contact_first_name"
     */
    public function testPropertyContactFirstName()
    {
    }

    /**
     * Test attribute "contact_last_name"
     */
    public function testPropertyContactLastName()
    {
    }

    /**
     * Test attribute "contact_middle_name"
     */
    public function testPropertyContactMiddleName()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "due_date_start"
     */
    public function testPropertyDueDateStart()
    {
    }

    /**
     * Test attribute "due_date_end"
     */
    public function testPropertyDueDateEnd()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "insert_timestamp"
     */
    public function testPropertyInsertTimestamp()
    {
    }

    /**
     * Test attribute "job_title"
     */
    public function testPropertyJobTitle()
    {
    }

    /**
     * Test attribute "main_candidate_id"
     */
    public function testPropertyMainCandidateId()
    {
    }

    /**
     * Test attribute "main_company_id"
     */
    public function testPropertyMainCompanyId()
    {
    }

    /**
     * Test attribute "main_contact_id"
     */
    public function testPropertyMainContactId()
    {
    }

    /**
     * Test attribute "main_entity_type"
     */
    public function testPropertyMainEntityType()
    {
    }

    /**
     * Test attribute "main_position_id"
     */
    public function testPropertyMainPositionId()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }
}
