<?php
/**
 * ActivitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ActivitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActivitiesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for activityCommentCommentIdCandidatesGet
     *
     * GET Comment's linked Candidates.
     *
     */
    public function testActivityCommentCommentIdCandidatesGet()
    {
    }

    /**
     * Test case for activityCommentCommentIdCategoriesGet
     *
     * GET Comment's categories.
     *
     */
    public function testActivityCommentCommentIdCategoriesGet()
    {
    }

    /**
     * Test case for activityCommentCommentIdCompaniesGet
     *
     * GET Comment's linked Companies.
     *
     */
    public function testActivityCommentCommentIdCompaniesGet()
    {
    }

    /**
     * Test case for activityCommentCommentIdContactsGet
     *
     * GET Comment's linked Contacts.
     *
     */
    public function testActivityCommentCommentIdContactsGet()
    {
    }

    /**
     * Test case for activityCommentCommentIdGet
     *
     * GET Comment basic info.
     *
     */
    public function testActivityCommentCommentIdGet()
    {
    }

    /**
     * Test case for activityCommentCommentIdPositionsGet
     *
     * GET Comment's linked Jobs.
     *
     */
    public function testActivityCommentCommentIdPositionsGet()
    {
    }

    /**
     * Test case for activityMeetingCommentIdCandidatesGet
     *
     * GET Meeting's linked Candidates.
     *
     */
    public function testActivityMeetingCommentIdCandidatesGet()
    {
    }

    /**
     * Test case for activityMeetingCommentIdCategoriesGet
     *
     * GET Meeting's categories.
     *
     */
    public function testActivityMeetingCommentIdCategoriesGet()
    {
    }

    /**
     * Test case for activityMeetingCommentIdGet
     *
     * GET Meeting basic info.
     *
     */
    public function testActivityMeetingCommentIdGet()
    {
    }

    /**
     * Test case for activityMeetingCommentIdStatusPut
     *
     * Complete Meeting.
     *
     */
    public function testActivityMeetingCommentIdStatusPut()
    {
    }

    /**
     * Test case for activityMeetingIdAttendeesGet
     *
     * GET Meeting's attendees.
     *
     */
    public function testActivityMeetingIdAttendeesGet()
    {
    }

    /**
     * Test case for activityMeetingIdCompaniesGet
     *
     * GET Meeting's linked Companies.
     *
     */
    public function testActivityMeetingIdCompaniesGet()
    {
    }

    /**
     * Test case for activityMeetingIdContactsGet
     *
     * GET Meeting's linked Contacts.
     *
     */
    public function testActivityMeetingIdContactsGet()
    {
    }

    /**
     * Test case for activityMeetingIdPositionsGet
     *
     * GET Meeting's linked Jobs.
     *
     */
    public function testActivityMeetingIdPositionsGet()
    {
    }

    /**
     * Test case for activityMeetingListRangeGet
     *
     * GET Meeting basic info on range start_date - end_date.
     *
     */
    public function testActivityMeetingListRangeGet()
    {
    }

    /**
     * Test case for activityTaskListRangeGet
     *
     * GET Task basic info on range start_date - end_date.
     *
     */
    public function testActivityTaskListRangeGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdCandidatesGet
     *
     * GET Task's linked Candidates.
     *
     */
    public function testActivityTaskTaskIdCandidatesGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdCategoriesGet
     *
     * GET Task's categories.
     *
     */
    public function testActivityTaskTaskIdCategoriesGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdCompaniesGet
     *
     * GET Task's linked Companies.
     *
     */
    public function testActivityTaskTaskIdCompaniesGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdContactsGet
     *
     * GET Task's linked Contacts.
     *
     */
    public function testActivityTaskTaskIdContactsGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdFollowersGet
     *
     * GET Task's followers.
     *
     */
    public function testActivityTaskTaskIdFollowersGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdGet
     *
     * GET Task basic info.
     *
     */
    public function testActivityTaskTaskIdGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdPositionsGet
     *
     * GET Task's linked Jobs.
     *
     */
    public function testActivityTaskTaskIdPositionsGet()
    {
    }

    /**
     * Test case for activityTaskTaskIdStatusPut
     *
     * Complete Task.
     *
     */
    public function testActivityTaskTaskIdStatusPut()
    {
    }

    /**
     * Test case for createComment
     *
     * POST: Create Comment.
     *
     */
    public function testCreateComment()
    {
    }

    /**
     * Test case for createMeeting
     *
     * POST: Create Meeting.
     *
     */
    public function testCreateMeeting()
    {
    }

    /**
     * Test case for createTask
     *
     * POST: Create Task.
     *
     */
    public function testCreateTask()
    {
    }

    /**
     * Test case for searchCandidateActivities
     *
     * POST: Search candidate's activities.
     *
     */
    public function testSearchCandidateActivities()
    {
    }

    /**
     * Test case for searchCompanyActivities
     *
     * POST: Search company's activities.
     *
     */
    public function testSearchCompanyActivities()
    {
    }

    /**
     * Test case for searchContactActivities
     *
     * POST: Search contact's activities.
     *
     */
    public function testSearchContactActivities()
    {
    }

    /**
     * Test case for searchPositionActivities
     *
     * POST: Search position's activities.
     *
     */
    public function testSearchPositionActivities()
    {
    }

    /**
     * Test case for searchUserActivities
     *
     * POST: Search user's activities.
     *
     */
    public function testSearchUserActivities()
    {
    }
}
