<?php
/**
 * ApplicationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ApplicationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for applicationBulkPost
     *
     * POST: Create job applications.
     *
     */
    public function testApplicationBulkPost()
    {
    }

    /**
     * Test case for applicationIdDelete
     *
     * DELETE: Delete Applications.
     *
     */
    public function testApplicationIdDelete()
    {
    }

    /**
     * Test case for applicationIdStageNextInterviewPost
     *
     * POST: move application forward to stage interview.
     *
     */
    public function testApplicationIdStageNextInterviewPost()
    {
    }

    /**
     * Test case for applicationIdStageNextOfferedPost
     *
     * POST: move application forward to stage offered.
     *
     */
    public function testApplicationIdStageNextOfferedPost()
    {
    }

    /**
     * Test case for applicationIdStageNextOnboardingPost
     *
     * POST: move application forward to stage onboarding.
     *
     */
    public function testApplicationIdStageNextOnboardingPost()
    {
    }

    /**
     * Test case for applicationIdStageNextPlacedPost
     *
     * POST: move application forward to stage placed.
     *
     */
    public function testApplicationIdStageNextPlacedPost()
    {
    }

    /**
     * Test case for applicationIdStageNextSentPost
     *
     * POST: move application forward to stage sent.
     *
     */
    public function testApplicationIdStageNextSentPost()
    {
    }

    /**
     * Test case for applicationLogListRangeGet
     *
     * GET: Get application logs on range.
     *
     */
    public function testApplicationLogListRangeGet()
    {
    }

    /**
     * Test case for applicationPost
     *
     * POST: Create job application.
     *
     */
    public function testApplicationPost()
    {
    }

    /**
     * Test case for applicationSubstatusUpdate
     *
     * PUT: Update Application's Substatus.
     *
     */
    public function testApplicationSubstatusUpdate()
    {
    }

    /**
     * Test case for candidateIdApplicationsStatusGet
     *
     * GET: Get summary status of each applications of candidate.
     *
     */
    public function testCandidateIdApplicationsStatusGet()
    {
    }

    /**
     * Test case for countAppByCandAndStage
     *
     * POST: count candidate's applications by stage.
     *
     */
    public function testCountAppByCandAndStage()
    {
    }

    /**
     * Test case for countAppByFilter
     *
     * POST: Count applications by filter.
     *
     */
    public function testCountAppByFilter()
    {
    }

    /**
     * Test case for countAppByPosAndStage
     *
     * POST: Count job's applications by stage.
     *
     */
    public function testCountAppByPosAndStage()
    {
    }

    /**
     * Test case for countAppByStage
     *
     * POST: Count applications by stage.
     *
     */
    public function testCountAppByStage()
    {
    }

    /**
     * Test case for getAppByCand
     *
     * GET: candidate's applications.
     *
     */
    public function testGetAppByCand()
    {
    }

    /**
     * Test case for getAppByCandAndStage
     *
     * POST: search candidate's applications by stage.
     *
     */
    public function testGetAppByCandAndStage()
    {
    }

    /**
     * Test case for getAppByFilter
     *
     * POST: search applications by filter.
     *
     */
    public function testGetAppByFilter()
    {
    }

    /**
     * Test case for getAppById
     *
     * GET: Application details.
     *
     */
    public function testGetAppById()
    {
    }

    /**
     * Test case for getAppByPos
     *
     * GET: job's applications.
     *
     */
    public function testGetAppByPos()
    {
    }

    /**
     * Test case for getAppByPosAndStage
     *
     * POST: search job's applications by stage.
     *
     */
    public function testGetAppByPosAndStage()
    {
    }

    /**
     * Test case for getAppByStage
     *
     * POST: search applications by stage.
     *
     */
    public function testGetAppByStage()
    {
    }

    /**
     * Test case for getAppLogById
     *
     * GET: Get application stage logs.
     *
     */
    public function testGetAppLogById()
    {
    }

    /**
     * Test case for rejectApplication
     *
     * POST: Reject Application.
     *
     */
    public function testRejectApplication()
    {
    }
}
