<?php
/**
 * ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for candidateId
     *
     * GET: candidate first location by country_code.
     *
     */
    public function testCandidateId()
    {
    }

    /**
     * Test case for contactId
     *
     * GET: Contact first location by country_code.
     *
     */
    public function testContactId()
    {
    }

    /**
     * Test case for contactIdDelete
     *
     * DELETE: Delete a contact.
     *
     */
    public function testContactIdDelete()
    {
    }

    /**
     * Test case for contactIdExternalmapPut
     *
     * PUT: Set a contact external_map.
     *
     */
    public function testContactIdExternalmapPut()
    {
    }

    /**
     * Test case for createContact
     *
     * POST: Create Contact.
     *
     */
    public function testCreateContact()
    {
    }

    /**
     * Test case for gETContact
     *
     * GET: Contact details.
     *
     */
    public function testGETContact()
    {
    }

    /**
     * Test case for getContactCustomFields
     *
     * GET: custom fields.
     *
     */
    public function testGetContactCustomFields()
    {
    }

    /**
     * Test case for getContactFunctionalExpertises
     *
     * GET: Functional Expertise.
     *
     */
    public function testGetContactFunctionalExpertises()
    {
    }

    /**
     * Test case for getContactJobs
     *
     * GET: Contact's linked jobs.
     *
     */
    public function testGetContactJobs()
    {
    }

    /**
     * Test case for getContactPersonalLocation
     *
     * GET: personal location.
     *
     */
    public function testGetContactPersonalLocation()
    {
    }

    /**
     * Test case for getContactSubfunctionalExpertise
     *
     * GET: Subfunctional Expertise.
     *
     */
    public function testGetContactSubfunctionalExpertise()
    {
    }

    /**
     * Test case for getContactWebappURL
     *
     * GET: Contact screen in Vincere web application.
     *
     */
    public function testGetContactWebappURL()
    {
    }

    /**
     * Test case for getContactWorkLocations
     *
     * GET: All Contact's work locations.
     *
     */
    public function testGetContactWorkLocations()
    {
    }

    /**
     * Test case for getContactsIndustries
     *
     * GET: industries.
     *
     */
    public function testGetContactsIndustries()
    {
    }

    /**
     * Test case for linkContactFuncAndSubFuncExpertises
     *
     * PUT: link Functional Expertise And Subfunctional Expertise.
     *
     */
    public function testLinkContactFuncAndSubFuncExpertises()
    {
    }

    /**
     * Test case for linkContactSubfunctionalExpertises
     *
     * PUT: link Subfunctional Expertise.
     *
     */
    public function testLinkContactSubfunctionalExpertises()
    {
    }

    /**
     * Test case for linkContactWithFunctionalExpertises
     *
     * PUT: link Functional Expertise.
     *
     */
    public function testLinkContactWithFunctionalExpertises()
    {
    }

    /**
     * Test case for linkWithIndustries
     *
     * PUT: link industries.
     *
     */
    public function testLinkWithIndustries()
    {
    }

    /**
     * Test case for postContactWorkLocation
     *
     * POST: Contact's work locations.
     *
     */
    public function testPostContactWorkLocation()
    {
    }

    /**
     * Test case for putContactCustomFields
     *
     * PUT: create or update custom fields.
     *
     */
    public function testPutContactCustomFields()
    {
    }

    /**
     * Test case for putContactHotPeriod
     *
     * PUT: Set a contact as hot contact.
     *
     */
    public function testPutContactHotPeriod()
    {
    }

    /**
     * Test case for putContactPersonalLocation
     *
     * PUT: create or update personal location.
     *
     */
    public function testPutContactPersonalLocation()
    {
    }

    /**
     * Test case for putContactWorkLocation
     *
     * PUT: Contact's work locations.
     *
     */
    public function testPutContactWorkLocation()
    {
    }

    /**
     * Test case for updateContact
     *
     * PUT: Update Contact.
     *
     */
    public function testUpdateContact()
    {
    }
}
