<?php
/**
 * JobApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * JobApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createJob
     *
     * POST: Create job.
     *
     */
    public function testCreateJob()
    {
    }

    /**
     * Test case for createJobRatingSkills
     *
     * PUT: create or recreate rating skills.
     *
     */
    public function testCreateJobRatingSkills()
    {
    }

    /**
     * Test case for editRatingSkill
     *
     * PUT: edit a rating skill.
     *
     */
    public function testEditRatingSkill()
    {
    }

    /**
     * Test case for editScreeningQuestion
     *
     * PUT: edit a screening question.
     *
     */
    public function testEditScreeningQuestion()
    {
    }

    /**
     * Test case for gETAJob
     *
     * GET: View A Job.
     *
     */
    public function testGETAJob()
    {
    }

    /**
     * Test case for gETAJobCompensation
     *
     * GET: View A Job compensation.
     *
     */
    public function testGETAJobCompensation()
    {
    }

    /**
     * Test case for gETAJobPlacements
     *
     * GET: View placements of Job.
     *
     */
    public function testGETAJobPlacements()
    {
    }

    /**
     * Test case for getJobCustomFields
     *
     * GET: custom fields.
     *
     */
    public function testGetJobCustomFields()
    {
    }

    /**
     * Test case for getJobOnboardingRequiredDocuments
     *
     * GET: job's required documents for onboarding.
     *
     */
    public function testGetJobOnboardingRequiredDocuments()
    {
    }

    /**
     * Test case for getJobRatingSkills
     *
     * GET: rating skills.
     *
     */
    public function testGetJobRatingSkills()
    {
    }

    /**
     * Test case for getLinkedFunctionalExpertises
     *
     * GET: functional expertises.
     *
     */
    public function testGetLinkedFunctionalExpertises()
    {
    }

    /**
     * Test case for getLinkedOwners
     *
     * GET: job's owners.
     *
     */
    public function testGetLinkedOwners()
    {
    }

    /**
     * Test case for getLinkedScreeningQuestions
     *
     * GET: Screening Questions.
     *
     */
    public function testGetLinkedScreeningQuestions()
    {
    }

    /**
     * Test case for getLinkedSubfunctionalExpertise
     *
     * GET: subfunctional expertises.
     *
     */
    public function testGetLinkedSubfunctionalExpertise()
    {
    }

    /**
     * Test case for linkJobFuncAndSubFuncExpertises
     *
     * PUT: link Functional Expertise And Subfunctional Expertise.
     *
     */
    public function testLinkJobFuncAndSubFuncExpertises()
    {
    }

    /**
     * Test case for linkWithFunctionalExpertises
     *
     * PUT: link functional expertises.
     *
     */
    public function testLinkWithFunctionalExpertises()
    {
    }

    /**
     * Test case for linkWithOwners
     *
     * PUT: link owners.
     *
     */
    public function testLinkWithOwners()
    {
    }

    /**
     * Test case for linkWithScreeningQuestions
     *
     * PUT: create or recreate screening questions.
     *
     */
    public function testLinkWithScreeningQuestions()
    {
    }

    /**
     * Test case for linkWithSubfunctionalExpertises
     *
     * PUT: link subfunctional expertises.
     *
     */
    public function testLinkWithSubfunctionalExpertises()
    {
    }

    /**
     * Test case for putJobCustomFields
     *
     * PUT: create or update custom fields.
     *
     */
    public function testPutJobCustomFields()
    {
    }

    /**
     * Test case for updateJob
     *
     * PUT: Update job.
     *
     */
    public function testUpdateJob()
    {
    }
}
