<?php
/**
 * ReferencesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vincere REST API
 *
 * Last updated date: **2019-12-03**  Change log on **[GitHub](https://github.com/vincere-io/restful-api-support)**
 *
 * OpenAPI spec version: 2-oas3
 * Contact: integration@vincere.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ReferencesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReferencesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for candidatesourcesGet
     *
     * Reference list for Candidate Sources.
     *
     */
    public function testCandidatesourcesGet()
    {
    }

    /**
     * Test case for contactsourcesGet
     *
     * Reference list for Contact Sources.
     *
     */
    public function testContactsourcesGet()
    {
    }

    /**
     * Test case for defActivityCategoriesGet
     *
     * Reference list for all activity's categories.
     *
     */
    public function testDefActivityCategoriesGet()
    {
    }

    /**
     * Test case for defActivityKpisGet
     *
     * Reference list for KPI actions.
     *
     */
    public function testDefActivityKpisGet()
    {
    }

    /**
     * Test case for defAstutepayperiodsGet
     *
     * Reference list for all Astute pay cycle.
     *
     */
    public function testDefAstutepayperiodsGet()
    {
    }

    /**
     * Test case for defAstuteratesGet
     *
     * Reference list for all Astute Rate types.
     *
     */
    public function testDefAstuteratesGet()
    {
    }

    /**
     * Test case for defAstuterulesGet
     *
     * Reference list for all Astute rule types.
     *
     */
    public function testDefAstuterulesGet()
    {
    }

    /**
     * Test case for defBrandsGet
     *
     * Reference list for all Brand in Vincere.
     *
     */
    public function testDefBrandsGet()
    {
    }

    /**
     * Test case for defCalculatechargesGet
     *
     * Reference list for all Calculate charge types.
     *
     */
    public function testDefCalculatechargesGet()
    {
    }

    /**
     * Test case for defCandidateDocumenttypesGet
     *
     * Reference list for all candidate document types..
     *
     */
    public function testDefCandidateDocumenttypesGet()
    {
    }

    /**
     * Test case for defCandidatestatusesGet
     *
     * Reference list for candidate statuses.
     *
     */
    public function testDefCandidatestatusesGet()
    {
    }

    /**
     * Test case for defContactstagesGet
     *
     * Reference list for Contact Stage.
     *
     */
    public function testDefContactstagesGet()
    {
    }

    /**
     * Test case for defContractlengthtypesGet
     *
     * Reference list for all Contract length type.
     *
     */
    public function testDefContractlengthtypesGet()
    {
    }

    /**
     * Test case for defCountriesGet
     *
     * Reference list for countries.
     *
     */
    public function testDefCountriesGet()
    {
    }

    /**
     * Test case for defCurrenciesGet
     *
     * Reference list for currencies.
     *
     */
    public function testDefCurrenciesGet()
    {
    }

    /**
     * Test case for defDivisionsGet
     *
     * Reference list for all Division in Vincere.
     *
     */
    public function testDefDivisionsGet()
    {
    }

    /**
     * Test case for defEducationlevelsGet
     *
     * Reference list for education levels.
     *
     */
    public function testDefEducationlevelsGet()
    {
    }

    /**
     * Test case for defEmploymenttypesGet
     *
     * Reference list for employment types.
     *
     */
    public function testDefEmploymenttypesGet()
    {
    }

    /**
     * Test case for defFeemodeltypesGet
     *
     * Reference list for all Fee Model types.
     *
     */
    public function testDefFeemodeltypesGet()
    {
    }

    /**
     * Test case for defGendersGet
     *
     * Reference list for genders.
     *
     */
    public function testDefGendersGet()
    {
    }

    /**
     * Test case for defJobtypesGet
     *
     * Reference list for job types.
     *
     */
    public function testDefJobtypesGet()
    {
    }

    /**
     * Test case for defKpiMainentitytypesGet
     *
     * Reference list for all KPI action's main entity type.
     *
     */
    public function testDefKpiMainentitytypesGet()
    {
    }

    /**
     * Test case for defLanguagelevelsGet
     *
     * Reference list for language skill levels.
     *
     */
    public function testDefLanguagelevelsGet()
    {
    }

    /**
     * Test case for defLanguagesGet
     *
     * Reference list for languages.
     *
     */
    public function testDefLanguagesGet()
    {
    }

    /**
     * Test case for defLocationsGet
     *
     * Reference list for all user Location in Vincere.
     *
     */
    public function testDefLocationsGet()
    {
    }

    /**
     * Test case for defMaritalstatusesGet
     *
     * Reference list for marital status.
     *
     */
    public function testDefMaritalstatusesGet()
    {
    }

    /**
     * Test case for defMeetingstatusesGet
     *
     * Reference list for meeting status.
     *
     */
    public function testDefMeetingstatusesGet()
    {
    }

    /**
     * Test case for defNationalitiesGet
     *
     * Reference list for nationalities.
     *
     */
    public function testDefNationalitiesGet()
    {
    }

    /**
     * Test case for defPaycalculationsGet
     *
     * Reference list for all total pay calculation types.
     *
     */
    public function testDefPaycalculationsGet()
    {
    }

    /**
     * Test case for defPayintervalsGet
     *
     * Reference pay interval list for contract-related jobs.
     *
     */
    public function testDefPayintervalsGet()
    {
    }

    /**
     * Test case for defPaymethodsGet
     *
     * Reference list for all Pay Method.
     *
     */
    public function testDefPaymethodsGet()
    {
    }

    /**
     * Test case for defRelocationsGet
     *
     * Reference list for relocation potentials.
     *
     */
    public function testDefRelocationsGet()
    {
    }

    /**
     * Test case for defSalarytypesGet
     *
     * Reference salary type list for permanent jobs.
     *
     */
    public function testDefSalarytypesGet()
    {
    }

    /**
     * Test case for defStagesGet
     *
     * Reference list for stages of an Application.
     *
     */
    public function testDefStagesGet()
    {
    }

    /**
     * Test case for defTeamsGet
     *
     * Reference list for all Team in Vincere.
     *
     */
    public function testDefTeamsGet()
    {
    }

    /**
     * Test case for defTimetypesGet
     *
     * Reference list for all Time Management types.
     *
     */
    public function testDefTimetypesGet()
    {
    }

    /**
     * Test case for functionalexpertiseIdSubfunctionalexpertisesGet
     *
     * Reference list for Sub-Functional Expertise of the given functional expertise.
     *
     */
    public function testFunctionalexpertiseIdSubfunctionalexpertisesGet()
    {
    }

    /**
     * Test case for functionalexpertisesGet
     *
     * Reference list for functional expertise, or skills.
     *
     */
    public function testFunctionalexpertisesGet()
    {
    }

    /**
     * Test case for getAppSubstatus
     *
     * GET: substatus of application.
     *
     */
    public function testGetAppSubstatus()
    {
    }

    /**
     * Test case for getCandConfFields
     *
     * GET: Candidate's custom fields.
     *
     */
    public function testGetCandConfFields()
    {
    }

    /**
     * Test case for getCompConfFields
     *
     * GET: Company's custom fields.
     *
     */
    public function testGetCompConfFields()
    {
    }

    /**
     * Test case for getContConfFields
     *
     * GET: Contact's custom fields.
     *
     */
    public function testGetContConfFields()
    {
    }

    /**
     * Test case for getPosConfFields
     *
     * GET: Job's custom fields.
     *
     */
    public function testGetPosConfFields()
    {
    }

    /**
     * Test case for industriesGet
     *
     * Reference list for Industries.
     *
     */
    public function testIndustriesGet()
    {
    }

    /**
     * Test case for subfunctionalexpertisesGet
     *
     * Reference list for Sub-Functional Expertise.
     *
     */
    public function testSubfunctionalexpertisesGet()
    {
    }
}
